### ISSUE TITLE
Add Pycon talk link to docs

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#102]
Add the Pycon talk link in the docs!

**Comment by Polokghosh53** [comment]
Hi @sansyrox 
Would like to work on this issue but was not able to find a link to the Pycon talk. Would you mind to share it?
Also, where exactly in the docs do you want to add the link to ? Is it the Readme.md or something else?

**Comment by sansyrox** [comment]
Hi @Polokghosh53 , thank you for volunteering.

Here is the talk link: https://www.youtube.com/watch?v=DK9teAs72Do

A sub heading in the readme works well for me. :D

**Comment by Polokghosh53** [comment]
Sure, on to it!

**Comment by Polokghosh53** [comment]
Do let me know if its done properly.
