### ISSUE TITLE
Reveal Logo to be removed from Future Roadmap

### ISSUE THREAD

**Issue by shivaylamba** [sansyrox/robyn#107]
![image](https://user-images.githubusercontent.com/19529592/141213758-f027d0c5-18da-48e4-83f6-3ed025508aad.png)
Logo has already been revealed so can be removed from the list

**Comment by sansyrox** [comment]
Thank you @shivaylamba :D

This is the new link: https://github.com/sansyrox/robyn/blob/main/integration_tests/base_routes.py

Can you please update it?

**Comment by SanchithHegde** [comment]
@shivaylamba The file is available at [`docs/roadmap.md`](https://github.com/sansyrox/robyn/blob/main/docs/roadmap.md?plain=1#L5) in case you want to open a PR.

**Comment by shivaylamba** [comment]
This was already fixed so closing this issue.
