### ISSUE TITLE
Add PyPI classifiers

### ISSUE THREAD

**Issue by Kludex** [sansyrox/robyn#127]
We should add [PyPI classifiers](https://pypi.org/classifiers/). At least the ones for Python version support.

We can check how uvicorn, gunicorn, fastapi, flask, etc. add to their classifiers.

**Comment by sansyrox** [comment]
This is a very good idea. Thank you for the suggestion. I will have a read at the docs :D

**Comment by Kludex** [comment]
If you need any help, let me know.

**Comment by sansyrox** [comment]
> If you need any help, let me know.

Thank you. Will do! :D
