### ISSUE TITLE
Add Python linter setup

### ISSUE THREAD

**Issue by Kludex** [sansyrox/robyn#129]
What do you think about adding some tooling here? e.g. black, isort and flake8

**Comment by sansyrox** [comment]
I usually use format on save and use `black` as my linter. 

Adding a project-wide linter is definitely a good idea. Do you have some suggestions/strong feelings for the others?

**Comment by Kludex** [comment]
> Do you have some suggestions/strong feelings for the others?

You mean isort and flake8? Most of the projects that I'm aware add at least those :thinking: 

> I usually use format on save and use black as my linter.

Are you sure? :thinking: Because I do that as well, and it was automatically formatting some files there.

**Comment by sansyrox** [comment]
> Are you sure? 🤔 Because I do that as well, and it was automatically formatting some files there.

Probably my editor was misconfigured then. But a project-wide linter is a good approach. 

What the pro(s)/con(s) of using more than one linter?
