### ISSUE TITLE
Add better support for requests and response!

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#13]
Use better pre built libraries instead of manually checking for GET, POST, etc.

**Comment by Saifu0** [comment]
When you say better pre-built libraries, you mean some wrapper for HTTP REST methods?

**Comment by sansyrox** [comment]
@sansyrox , yes. I also think I need to be more descriptive of the issues xD.

I would want to use some sort of request parser of hyper or some similar library.
