### ISSUE TITLE
[BUG] Default URL cannot be assigned

### ISSUE THREAD

**Issue by patchgamestudio** [sansyrox/robyn#159]
**Description**
When running `app.start()`, the default URL that Robyn assigns is `128.0.0.1`, which appears to be a [public IP in the Netherlands](https://awebanalysis.com/en/ip-lookup/128.0.0.1/). This causes the application to throw the following error on Ubuntu 20.04 (WSL2):
`OSError: Cannot assign requested address (os error 99)`
Windows error:
`OSError: The requested address is not valid in its context. (os error 10049)`

**Expected Behavior**
Most likely, the default URL was meant to be `127.0.0.1` which is the universal address for localhost. When running `app.start(url="127.0.0.1", port=5000)` or `app.start(url="0.0.0.0", port=5000)` the OSError is not encountered. Robyn runs successfully on Ubuntu, but still encounters [another known issue](https://github.com/sansyrox/robyn/issues/139) in Windows.

**Environment:**
Tested on both Windows 10 and Ubuntu 20.04 (WSL2 on Windows 10)
Robyn version: 0.12.0

**Comment by sansyrox** [comment]
Thank you for this bug report. I see some typo crept in the package release. I will fix the code and start a better unit testing system in the next release(also hopefully tomorrow).

Thank you!
