### ISSUE TITLE
Error on import 

### ISSUE THREAD

**Issue by harshraj22** [sansyrox/robyn#16]
![image](https://user-images.githubusercontent.com/46635452/122634884-7cdc1200-d0fe-11eb-9bf7-eb20c54a0120.png)

Error while running `test.py`. Did you forget adding files ?
Note: already cloned the repo, and also did `pip install robyn`

**Comment by sansyrox** [comment]
Hey @harshraj22 . Can you try installing maturin first?

`pip install --user maturin` and then run `maturin develop`?

**Comment by harshraj22** [comment]
@sansyrox not sure if there's some issue with the package, or something wrong with my system.


![image](https://user-images.githubusercontent.com/46635452/122663177-27fbd280-d1b6-11eb-9668-74bcc6f5e395.png)

**Comment by j0fiN** [comment]
@sansyrox, should rust be installed to work with this library?

**Comment by sansyrox** [comment]
@j0fiN , if you want just want to use via `pip3 install robyn` then no. But if you want to develop on it, then yes.

**Comment by sansyrox** [comment]
@j0fiN , did robyn work for you without using rust?

**Comment by sansyrox** [comment]
This should be fixed now. Closing this.
