### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by thewchan** [sansyrox/robyn#161]
Hi, I've been trying to build the newest version of robyn (v0.12.1) for distributing in conda-forge, but I've been getting this error during the build process:
```
  error[E0308]: mismatched types
     --> src/server.rs:160:33
      |
  160 |                 .client_timeout(0)
      |                                 ^ expected struct `std::time::Duration`, found integer

```

I've tried conforming to the rust version in the CI to no avail. Does anyone have any advice?

**Comment by sansyrox** [comment]
Hi @thewchan .

I will be happy to help. Can you please tell me the exact steps you took in the build process?

**Comment by sansyrox** [comment]
@thewchan , I can see that one of the library functions is deprecated in the error log, which is probably why the resulting error. Can you confirm if you get the same error in the latest version, i.e. 0.13.0 . If yes, I will make a new release with the updated dependencies.

**Comment by thewchan** [comment]
Thanks so much @sansyrox, really appreciate it. Hope this works!

**Comment by sansyrox** [comment]
Hi @thewchan , I just released v0.13.1. It is working well on my Pipeline. Can you please check if this works for you too?

**Comment by thewchan** [comment]
Thanks, I'll give it a try and report back!

**Comment by thewchan** [comment]
@sansyrox It built correctly now; thanks so much!

**Comment by sansyrox** [comment]
My Please @thewchan :D

Does this mean that robyn can also be installed via conda now?

**Comment by thewchan** [comment]
Indeed; earlier versions (0.10 I think) are already available via `conda install -c conda-forge robyn`
v0.13.1 will take a bit for the CI to go through completely
