### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by thewchan** [sansyrox/robyn#166]
Hi, getting another build error for 0.14.0; it's something with the rust compilation again: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=467486&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0

```
  error[E0277]: the trait bound `MyWs: actix::actor::Actor` is not satisfied
     --> src/web_socket_connection.rs:62:37
      |
  62  |     fn started(&mut self, ctx: &mut WebsocketContext<Self>) {
      |                                     ^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `MyWs`
      |
  note: required by a bound in `WebsocketContext`
     --> /home/conda/feedstock_root/build_artifacts/robyn_1646278130206/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.1.0/src/ws.rs:373:8
      |
  373 |     A: Actor<Context = WebsocketContext<A>>,
      |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebsocketContext`
```

There are five other errors that are similar/identical.

**Comment by sansyrox** [comment]
Oh, wow. This is not good. I suspect this has something to do with a new rust stable being released yesterday and robyn relying on a beta version of actix. 

No worries, I will take a look this.

**Comment by sansyrox** [comment]
Also, @thewchan i really appreciate you reporting issues here :D

**Comment by thewchan** [comment]
Newest version still incur the following errors:

```
  error[E0277]: the trait bound `MyWs: actix::actor::Actor` is not satisfied
     --> src/web_socket_connection.rs:28:15
      |
  28  |     ctx: &mut ws::WebsocketContext<MyWs>,
      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `MyWs`
      |
  note: required by a bound in `WebsocketContext`
     --> /home/conda/feedstock_root/build_artifacts/robyn_1648178634645/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.1.0/src/ws.rs:373:8
      |
  373 |     A: Actor<Context = WebsocketContext<A>>,
      |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebsocketContext`


  error[E0277]: the trait bound `MyWs: actix::actor::Actor` is not satisfied
     --> src/web_socket_connection.rs:75:20
      |
  75  |     type Context = ws::WebsocketContext<Self>;
      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `MyWs`
      |
  note: required by a bound in `WebsocketContext`
     --> /home/conda/feedstock_root/build_artifacts/robyn_1648178634645/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.1.0/src/ws.rs:373:8
      |
  For more information about this error, try `rustc --explain E0277`.

  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/conda/feedstock_root/build_artifacts/robyn_1648178634645/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
  error: subprocess-exited-with-error
```

**Comment by sansyrox** [comment]
@thewchan , I was able to finally figure out why this is happening. So, the build crashes every time the latest rust stable version is released(in every 6 weeks) as I am using a beta library for faster speeds.

Now, I am unable to see the logs(probably since they have expired) but ig I would need to be compiling it with the latest rust version or find some other alternative.

So, the build will be fixed in the next version released.

Thanks again. :D

**Comment by thewchan** [comment]
Thanks! I'll will keep an eye out and keep you posted.

**Comment by sansyrox** [comment]
Hi @thewchan , can you check if the build faillure has been fixed in the latest update?

**Comment by thewchan** [comment]
@sansyrox still not working out it seems. Can you access these build logs?
https://github.com/conda-forge/robyn-feedstock/pull/17/checks?check_run_id=6232337032

**Comment by sansyrox** [comment]
@thewchan , https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=499695&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0

I just read through this log. Is the docker image available on docker hub? Or can you point me to the config that is being used here?

I would like to replicate the issue but I am unable to do so.

**Comment by thewchan** [comment]
Do you mean the docker image for the rust distribution?

**Comment by sansyrox** [comment]
> Do you mean the docker image for the rust distribution?

Yess

**Comment by thewchan** [comment]
I will inquire and get back to you, thanks!

**Comment by sansyrox** [comment]
Thank you so much 😃

**Comment by thewchan** [comment]
https://github.com/conda-forge/docker-images

^^^ It seems that we don't pull a specific rust container but rather whatever is default in these linux containers?

**Comment by thewchan** [comment]
Here's what the admins said:

![image](https://user-images.githubusercontent.com/49702524/167477368-cc344df5-ede2-4a76-96c7-4929b98b6aa0.png)

**Comment by sansyrox** [comment]
Thank you so much @thewchan . I was able to replicate and fix the issues. Everything should be hopefully fixed in 0.16.2. Can you check once?

**Comment by thewchan** [comment]
Awesome, I'm waiting downstream for it to detect 0.16.2, will keep you posted

**Comment by thewchan** [comment]
Success! 
![image](https://user-images.githubusercontent.com/49702524/167652752-7a9d8abc-a8e1-4d4e-ba02-e745b920e709.png)

**Comment by sansyrox** [comment]
Yess!! Thanks @thewchan for all the help. Feel free to close the issue once you've merged the PR upstream :D
