### ISSUE TITLE
Optional build feature for io_uring

### ISSUE THREAD

**Issue by mwilli20** [sansyrox/robyn#177]
**Current Behavior**

Things are fast.

**Desired Behavior**

Things could be even faster 😹

If you haven't read much on io_uring I'd check it out. But what I'm thinking here is there could be an optional feature when building Robyn if you want to use io_uring

Since Robyn is using actix-web and they have an expiremental feature for io_uring you could have a similar feature here.

https://github.com/sansyrox/robyn/blob/main/Cargo.toml#L25
https://github.com/actix/actix-web/blob/09cffc093cd755d09a40a14f073f49015aa6e7ad/actix-web/Cargo.toml#L63

**Comment by sansyrox** [comment]
Hi @mwilli20 ,

This looks like an interesting feature :D

I'd have to see how to have os specific builds. If this branch doesn't change the API much, I don't think that should be hard.

Do you have any previous experience with it??

**Comment by mwilli20** [comment]
I have not played with this yet but was thinking it could be cool. I think it's as simple as using https://doc.rust-lang.org/cargo/reference/features.html and no API change as it just changes the underlying runtime in actix-web.

**Comment by sansyrox** [comment]
@mwilli20 , I just went through the docs. I can see that cargo supports features in a very simple way. 

But I am not sure if maturin(the tool that builds robyn for distribution) does.

I did read maturin's user guide and found this link(https://maturin.rs/distribution.html?highlight=option#build-wheels) helpful. But still couldn't understand what would I need to change here.

Maybe @messense can please help?

**Comment by messense** [comment]
@sansyrox You can use the `--cargo-extra-args` option to pass `--features`.

**Comment by sansyrox** [comment]
Thanks @messense , just went through the documentation again. Thank you! :D

@mwilli20, I will implement as an optional release in the next version :D

**Comment by mwilli20** [comment]
Amazing!

**Comment by sansyrox** [comment]
Implemented
