### ISSUE TITLE
Architecture link in readme redirects to raw content

### ISSUE THREAD

**Issue by RutvikJ77** [sansyrox/robyn#18]
Under the Contributor guideline section, the link for architecture redirects to raw content. It should redirect to 
https://github.com/sansyrox/robyn/blob/main/docs/architecture.md

Issue section:
https://github.com/sansyrox/robyn#contributor-guidelines

**Comment by sansyrox** [comment]
Thank you for the report! 😄 
Fixed here: https://github.com/sansyrox/robyn/commit/4708de98c736628414ce3b67e8430c0ef50cb29d
