### ISSUE TITLE
[Feature Request] Add list of sponsors on the project website 

### ISSUE THREAD

**Issue by shivaylamba** [sansyrox/robyn#182]
**Current Behavior**

Add list of sponsors for Robyn on the project website.

**Desired Behavior**

Have a section for list of sponsors for Robyn on the project website.

**Comment by sansyrox** [comment]
On it!

**Comment by sansyrox** [comment]
Done: https://github.com/sansyrox/robyn

**Comment by shivaylamba** [comment]
awesome
