### ISSUE TITLE
[Feature Request] Update the new architecture on the docs website

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#191]
**Current Behavior**

The website has an old architecture, update to a new one

**Desired Behavior**

---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by c00kiemon5ter** [comment]
The current doc has an abstract description of the system depicting the happy flow.

It would be great to include what happens when things go back in different phases of the processing pipeline, especially where races can happen or conflicting tasks are picked up.

**Comment by sansyrox** [comment]
<img width="832" alt="Screenshot 2022-04-29 at 9 13 28 PM" src="https://user-images.githubusercontent.com/29942790/166160046-e45d721a-0b3a-4e13-ad18-f30892274bfe.png">


Hi @c00kiemon5ter , 

Thank you for your comments. But this is the latest architecture diagram that I have. 

> It would be great to include what happens when things go back in different phases of the processing pipeline, especially where races can happen or conflicting tasks are picked up.

I don't completely understand what you mean by this. Do you want me to also show where the possible errors may happen?

Do you have an example that you could share with me?
