### ISSUE TITLE
[BUG] Move away from circle ci

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#240]
**Description**
Need to move away from circle ci as it is unnecessary. I would like to move everything to github actions.

**Expected Behavior**

Move the build process github actions.

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

**Comment by AntoineRR** [comment]
Hi, I will try to do this as I already worked on the CI previously

**Comment by sansyrox** [comment]
@AntoineRR , thank you! Do let me know if you have any questions :D
