### ISSUE TITLE
[Feature Request] fix clippy issues

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#265]
**Current Behavior**

Clippy has issues

**Desired Behavior**

Fix them

---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by Overflow0xFFFF** [comment]
I took a look into this issue as part of Hacktoberfest. Clippy has an issue with PyO3 projects that appears will be fixed with Rust 1.65 (See https://github.com/rust-lang/rust-clippy/issues/8971#issuecomment-1214112284). An initial run of `cargo clippy -- -W clippy::all` shows that 9 out of the 10 warnings relate to that issue and will potentially go away with Rust 1.65.

**Comment by sansyrox** [comment]
Ah, perfect. That is good news @Overflow0xFFFF :D

What is the 10th warning?

**Comment by Overflow0xFFFF** [comment]
@sansyrox: Using a `match` instead of `if let` due to an empty arm of the match statement throws this warning:

```
warning: you seem to be trying to use `match` for destructuring a single pattern. Consider using `if let`
   --> src/server.rs:457:5
    |
457 | /     match middleware_router.get_route("AFTER_REQUEST", req.uri().path()) {
458 | |         Some(((handler_function, number_of_params), route_params)) => {
459 | |             let x = handle_http_middleware_request(
460 | |                 handler_function,
...   |
471 | |         None => {}
472 | |     };
    | |_____^
    |
    = note: `-W clippy::single-match` implied by `-W clippy::all`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match
help: try this
    |
457 ~     if let Some(((handler_function, number_of_params), route_params)) = middleware_router.get_route("AFTER_REQUEST", req.uri().path()) {
458 +         let x = handle_http_middleware_request(
459 +             handler_function,
460 +             number_of_params,
461 +             &headers_dup,
462 +             &mut payload,
463 +             &req,
464 +             route_params,
465 +             queries.clone(),
466 +         )
467 +         .await;
468 +         debug!("{:?}", x);
469 ~     };
```

**Comment by sansyrox** [comment]
Perfect, thanks @Overflow0xFFFF . Do you want to create a PR for this ?

**Comment by Overflow0xFFFF** [comment]
I'm going to work with a friend on installing the Rust toolchain and seeing them through their first Hacktoberfest. Expect a PR shortly!

**Comment by sansyrox** [comment]
Hey @Overflow0xFFFF ,

Thank you for helping out new contributors to the repo. I really appreciate it 😊😊
