### ISSUE TITLE
[Feature Request] Add Digital Ocean to list of sponsors in Robyn Docs

### ISSUE THREAD

**Issue by shivaylamba** [sansyrox/robyn#270]
We should add Digital Ocean to the list of sponsors in docs: https://sansyrox.github.io/robyn/#/sponsors
Can be added to the PR for docs improvement: https://github.com/sansyrox/robyn/pull/269 @sansyrox

**Comment by sansyrox** [comment]
Thanks @shivaylamba . Done! :D
