### ISSUE TITLE
[BUG] README.md Discord link is invalid

### ISSUE THREAD

**Issue by Meldiron** [sansyrox/robyn#272]
**Description**

Link in the [README.md](https://github.com/sansyrox/robyn/blob/main/README.md) of this repo links to an invalid Discord invitation.

**Expected Behavior**

Valid invitation link.

**Screenshots**

![CleanShot 2022-08-29 at 11 41 32](https://user-images.githubusercontent.com/19310830/187173065-530a7a3b-db4f-49c2-bea0-29b17cc2a714.png)
---

[Optional] **Additional Context**

I believe the default behavior of the Discord invitation link is expiration after 1 week. When making a link, make sure to set expiration after `never` to resolve this problem infinitely. 

![CleanShot 2022-08-29 at 11 43 28](https://user-images.githubusercontent.com/19310830/187173364-f69a50ec-0945-4ab5-ac26-173f1015c403.png)

**Comment by sansyrox** [comment]
Thank you @Meldiron :smile: 

It has been fixed now. Here is the link btw: https://discord.com/invite/rkERZ5eNU8
