### ISSUE TITLE
[Feature Request] Add `@wraps` in route dectorators

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#285]
**Current Behavior**

Right now, we are not wrapping the route decorators. This leads to them losing the associated metadata.

**Desired Behavior**

Use `functools.wraps` to wrap the decorator.
---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by sansyrox** [comment]
@guilefoylegaurav , sure.

So, you can have a look here that `functool.wraps` helps in preserving metadata(name, magic methods of a function and so on.) here(https://stackoverflow.com/questions/308999/what-does-functools-wraps-do).

Now, robyn also has many decorators like here(https://github.com/sansyrox/robyn/blob/main/robyn/__init__.py#L185) . I wanted to check if we are still preserving the metadata or not

**Comment by guilefoylegaurav** [comment]
I see. I get the point. 
Basically, I was taking "metadata" to mean something else.

**Comment by sansyrox** [comment]
@guilefoylegaurav , are you working on this or can I take it up?

**Comment by guilefoylegaurav** [comment]
@sansyrox, you can take this up - I haven't been working on this actually. 
I have been exploring some other feature request issues that I can potentially contribute to.

**Comment by sansyrox** [comment]
@guilefoylegaurav , alright perfect.
