### ISSUE TITLE
[Feature Request?] Update `matchit` crate to the most recent version

### ISSUE THREAD

**Issue by fregataa** [sansyrox/robyn#291]
**Current Behavior**
Robyn uses `matchit` crate version **0.4.3** currently, and the most recent version of `matchit` is **0.6.0** for now 2022 Oct 10th.

**Desired Behavior**
We do not need to update `matchit` to "0.6.0" ASAP because it is also under development.
But we will have to update the dependency when the crate is *stable*.
I checked `matchit::Node` is replaced with `matchit::Router` and there can be other updates that I have not found.

---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by sansyrox** [comment]
Perfect. Thanks for the update. I will have a look at the updates.

**Comment by sansyrox** [comment]
This has been fixed in #298
