### ISSUE TITLE
[Feature Request] Cross Origin support similar to flask-cors

### ISSUE THREAD

**Issue by kamaravichow** [sansyrox/robyn#296]
**Desired Behavior**
Cross-Origin Request management for web apps as browsers block them if they are hosted on a different domain

**Alternatives**
We could manually add the headers

**Comment by sansyrox** [comment]
Thanks for the feature request @kamaravichow .

Do you happen to know the exact headers required?

**Comment by kamaravichow** [comment]
```
 'Access-Control-Allow-Origin'
'Access-Control-Allow-Methods'
 'Access-Control-Allow-Headers'
 'Access-Control-Expose-Headers'
 'Access-Control-Allow-Credentials'
'Access-Control-Max-Age'
```

These are a few important ones that I use in my APIs

**Comment by sansyrox** [comment]
@kamaravichow , these are request headers right?

**Comment by kamaravichow** [comment]
And the response header should contain this particular header to allow all the origins
```
Access-Control-Allow-Origin: *
```

**Comment by suhailmalik07** [comment]
@sansyrox, I can pick this up. If it's okay.
have a question regarding approach. 

Flask uses flask-cors [lib](https://flask-cors.readthedocs.io/en/latest/).

Which will be preferable creating a new lib(like flask-cors) or extending in same code-base?

**Comment by sansyrox** [comment]
Hey @suhailmalik07 👋 

Thank you. Since every developer almost uses cors, I think it makes sense to have it in our codebase.

**Comment by suhailmalik07** [comment]
Thanks for clarifying, I'm picking this up then.

**Comment by sansyrox** [comment]
@suhailmalik07 , do let me know if you require any help from my end. :D

**Comment by suhailmalik07** [comment]
Hey @sansyrox, Thanks for letting me know. Sorry, but I'm currently stuck with something else. If anyone else wants to pick this up, that will be okay. It will take me some time.

**Comment by Fazatholomew** [comment]
Hey @sansyrox, may I take this one? I am new to open source contribution but have coded in Python for a while. Rust, not so much. I want to discuss the approach for this. Where should I do that?

**Comment by sansyrox** [comment]
Hi @Fazatholomew 👋 

Apologies. This missed my eye. This issue has been addressed already. :(

However, feel free to pickup another issue. Let me know if you need any help 😄
