### ISSUE TITLE
[BUG] Wrong link for the blog post on Robyn

### ISSUE THREAD

**Issue by shivaylamba** [sansyrox/robyn#306]
**Description**

Wrong link for the blog post on Robyn in the documentation
The correct link is: https://www.sanskar.me/posts/hello-robyn

**Comment by sansyrox** [comment]
@shivaylamba , where have we mentioned the blog post? Can you please attach a screenshot?

**Comment by shivaylamba** [comment]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/19529592/201423096-50e899e0-43cb-4d0e-977f-dba781d9ee06.png">
@sansyrox the link to the blog post is wrong.

**Comment by shivaylamba** [comment]
https://sansyrox.github.io/robyn/#/community-resources

**Comment by shivaylamba** [comment]
Also on this note we should have a section for upcoming talks/sessions on Robyn as well in the #Community Resources
