### ISSUE TITLE
[BUG] Fix CI/CD pipeline

### ISSUE THREAD

**Issue by AntoineRR** [sansyrox/robyn#310]
**Description**

- The `Preview release` job fails for every PR.
- Also, when this job runs on master, it displays the following logs for every build:
```
WARNING  Skipping robyn-0.18.3-cp310-cp310-macosx_10_7_x86_64.whl because it    
         appears to already exist
```

If I understand correctly, the `Preview Release` job should be run for PRs only. In PRs, it seems the job is failing because of an authentication error:
```
ERROR    HTTPError: 403 Forbidden from https://test.pypi.org/legacy/            
         Invalid or non-existent authentication information. See                
         https://test.pypi.org/help/#invalid-auth for more information.
```
Maybe the `TEST_PYPI_PASSWORD` secret is not available in PRs which makes sense from a security point of view (see https://stackoverflow.com/questions/73866908/github-actions-main-repository-secret-not-picked-up-from-pull-request-build)

- The Rust CI displays warnings:
```
Node.js 12 actions are deprecated.
```
This is because the [actions-rs](https://github.com/actions-rs/toolchain) toolchain project is not maintained anymore.

**Expected Behavior**

Do not run the `Preview Release` job on push? Find a way to retrieve the secrets on PRs or maybe remove the job completely?

I know how to get rid of the warnings in the Rust pipeline, but would like some guidance on the `Preview Release` job purpose and fix if possible.

**Comment by sansyrox** [comment]
@AntoineRR , thank you for opening the issue and apologies for the late revert.

`Preview Release` job is an experimental job that I wrote to allow me to create and test a release on `test-pypi` before pushing it on the main `pypi`.

Disabling PR can be one way. But I think we can talk with the `pyo3` community to see if there's a better way to test the builds.

**Comment by AntoineRR** [comment]
Thanks for the info :)
Another solution could be to run the `Preview Release` job on push to `main` branch only (when a PR is merged). Then the `Release` job could run only if a tag is associated with the commit and after the `Preview Release` job succeeded (`Preview Release` and `Release` job run in parallel instead of sequentially currently).
What do you think about that?
