### ISSUE TITLE
[BUG] Error in Examples section in Documentation

### ISSUE THREAD

**Issue by carlosm27** [sansyrox/robyn#314]
**Description**

There is an error in the Examples section. The code snippet in "Using Middleware" is the same of  "Serving simple HTML Files"

**Expected Behavior**

The code snippet should be :
```
@app.before_request("/")
async def hello_before_request(request):
    print(request)


@app.after_request("/")
def hello_after_request(request):
    print(request)
```

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

**Comment by sansyrox** [comment]
Thank you @carlosm27 . I am on it 😄

**Comment by carlosm27** [comment]
I can do that

**Comment by sansyrox** [comment]
Apologies Carlos,

I just saw your message.
