### ISSUE TITLE
Forced shutdown locks console. [BUG]

### ISSUE THREAD

**Issue by Alteian** [sansyrox/robyn#317]
While forcing down the server console remains locked.

WinOS11 -V 22H2 build 22621.819
console: Git Bash, CMD

![image](https://user-images.githubusercontent.com/90640802/203052635-5c20b0e0-5213-43b2-8d2c-896e1f947e25.png)

**Comment by sansyrox** [comment]
Thanks @Alteian for raising the issue. I'll set up a dual boot by this weekend, and then I will try to fix this.

**Comment by AntoineRR** [comment]
Hey @sansyrox, is this fixed with #391 ?

**Comment by sansyrox** [comment]
Hey @AntoineRR , yep :D
