### ISSUE TITLE
[BUG] Custom headers not sent when const=False

### ISSUE THREAD

**Issue by cirospaciari** [sansyrox/robyn#323]
**Description**

Custom header is only sent when const=True
**Expected Behavior**

Custom header must always be sent even without const=True

**Environment:**
- Host OS: Debian GNU/Linux bookworm/sid x86_64 Kernel 6.0.0-2-amd64
- Browser:  Chrome 107.0.5304.110

---

[Optional] **Additional Context**

When using const=False no Custom headers are sent.
```python
app.add_header("Server", "Robyn")
app.add_header("Content-Type", "text/plain")
```

```python
@app.get('/plaintext')
def plaintext() -> str:
    return "Hello, world!"
```
When using const=True Date headers are sent.
```python
@app.get('/plaintext', const=True)
def plaintext() -> str:
    return "Hello, world!"
    
```
I just find this, when trying to run TechEmPower Benchmarks without const

---

**Comment by sansyrox** [comment]
Thank you @cirospaciari for opening this issue 😄 

Can you please elaborate on what you mean by the Date headers?

**Comment by cirospaciari** [comment]
Sorry actually i miss understood the issue, whats is happens is:
After adding this custom headers
```python
app.add_header("Server", "Robyn")
app.add_header("Content-Type", "text/plain")
```
Withou const=True the headers are not sent.
Date header is fine

**Comment by sansyrox** [comment]
@cirospaciari , this shouldn't happen. Will have to investigate. Thanks!
