### ISSUE TITLE
[Feature Request] Hope robyn can support returning f-string format

### ISSUE THREAD

**Issue by shaohaiyang** [sansyrox/robyn#338]
**Current Behavior**
Could not support return f-string response

for example:

![image](https://user-images.githubusercontent.com/2763056/207870553-ac712b02-c3e9-4ad6-9142-24e6a7a5bdc1.png)

**Comment by sansyrox** [comment]
Hey @shaohaiyang . Robyn does support returning f-strings. For example something like this will work

```
from robyn import Robyn

app = Robyn(__file__)


@app.get('/')
def index():
    var = "world"
    return f"Hello, {var}"


if __name__ == "__main__":
    app.start(port=8000)

```


However, you are trying to return an HTML. You can either use templates(https://sansyrox.github.io/robyn/#/features?id=templates) or static_file(https://sansyrox.github.io/robyn/#/examples?id=serving-simple-html-files)) to serve the HTML.

**Comment by sansyrox** [comment]
I hope that helps. Lmk if you need some other information. Or we can close this issue. 😄

**Comment by shaohaiyang** [comment]
Thank you very much for your reply. According to my test, """ is not supported, but it can be supported by newline formatting. 

![image](https://user-images.githubusercontent.com/2763056/208004337-a4baa579-acf4-4223-adf3-84c2811125d8.png)

So, this issue could be close.

BTW, I'm testing using robyn, htmx in a new project. It is a good idea.

**Comment by shaohaiyang** [comment]
@sansyrox ，If it can support f """ format, it will works better with jinja2.  

> Thank you very much for your reply. According to my test, """ is not supported, but it can be supported by newline formatting.

**Comment by sansyrox** [comment]
@shaohaiyang , the traditional `f-string` format should already work. I will add some documentation regarding it today :D

**Comment by sansyrox** [comment]
@shaohaiyang ,

can you try if this works for you

```python
from robyn import Robyn, jsonify
from pathlib import Path
import os


app = Robyn(__file__)


@app.get("/")
def template_render():
    context = {"title": "Hello World!", "description": "This is a description"}
    return {
        "status": "200",
        "body": f"""<html>Hellow { context['title'] }</html>""",
        "headers": jsonify({"Content-Type": "text/html"}),
    }


if __name__ == "__main__":
    app.start(port=8000)

```

**Comment by shaohaiyang** [comment]
yes，it can works but also need backslash :(

**Comment by sansyrox** [comment]
@shaohaiyang , actually no.

This works now :D

Without backslash! :D

```python
from robyn import Robyn, jsonify
from pathlib import Path
import os


app = Robyn(__file__)


@app.get("/")
def template_render():
    context = {"title": "Hello World!", "description": "This is a description"}
    return {
        "status": "200",
        "body": f"""
        <html>Hellow { context['title'] }
        <p>{ context['description'] }</p>
        </html>""",
        "headers": {"Content-Type": "text/html"},
    }


if __name__ == "__main__":
    app.start(port=8000)

```

**Comment by shaohaiyang** [comment]
Yes, It works very well when i upgrade robyn to latest  verson 0.20.0, thanks  again very much .

**Comment by sansyrox** [comment]
Perfect. I am glad it works! :D
