### ISSUE TITLE
[BUG] Get Stared failed on Windows

### ISSUE THREAD

**Issue by Paroxyste** [sansyrox/robyn#340]
In order to try to solve the problem #339 of the render_template, I wanted to make a fresh install on my windows laptop.

I installed Python 3.10.9, Robyn and Jinja2, then I copy/pasted the Get Started code from the doc and when I launch it I get this error :

![image](https://user-images.githubusercontent.com/120705504/208251861-82ba7aad-7b9a-4bcc-8ab3-abfd0feefebe.png)

main.py

```python
from robyn import Robyn

app = Robyn(__file__)

@app.get("/")
async def h(request): # request is an optional parameter
    return "Hello, world!"

app.start(port=5000, url="0.0.0.0")
```

I launch program with :

```
python app.py
```

My package version :

![image](https://user-images.githubusercontent.com/120705504/208251958-3ec8bc1b-dd19-495d-a205-03aed50c6b5f.png)

And my structure project got only app.py file

Robyn work on windows ?  or is it another problem ?

I apologize for bothering you with these problems but I really want to use this great framework for my projects.

**Comment by sansyrox** [comment]
> I apologize for bothering you with these problems but I really want to use this great framework for my projects.

No worries. I really appreciate you helping with all the support 😄 

I will have a look. Ideally, this should work.

**Comment by MosTafa2K** [comment]
i have same problem too!

when i lunch code from the doc i get this error.

OS: Windows 10
Python: 3.9.6
Robyn: 0.20.0

**Comment by sansyrox** [comment]
@MosTafa2K @Paroxyste , this should be fixed in the latest release. Can you folks please have a look?

**Comment by sansyrox** [comment]
I just tested on Windows 10 on the latest version of Robyn and everything is working well :D
