### ISSUE TITLE
[Feature Request] Support for image file type

### ISSUE THREAD

**Issue by DhruvThu** [sansyrox/robyn#343]
Hey, I am new to Robyn framework. Can someone help me to provide an image as response to get request? 

Thanks!!

**Comment by sansyrox** [comment]
Hey @DhruvThu ,

Right now, you can use something like this:

```
@app.get("/image")
def return_image():
    return {
        "status": "200",
        "body": Path("test.png").read_bytes(),
        "headers": {"Content-Type": "image/png"},
    }

```

But this is a good idea, I will create a helper function for it.

**Comment by DhruvThu** [comment]
Hey, Thank you so much for quick support. I have tried with the code which you have sent. But I am getting this error. 

thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'TypeError'>, value: TypeError("'bytes' object cannot be converted to 'PyString'"), traceback: None }', src/executors/mod.rs:89:47

**Comment by sansyrox** [comment]
I think you are using an async function right now. It only works with `sync` functions right now 😅

**Comment by DhruvThu** [comment]
I have tried to run code after removing async. Code is working but I am getting a broken image when I run localhost. My code is as follows:

from robyn import Robyn
from PIL import Image
import pathlib
import numpy as np
import io
import urllib.parse

  
  

app = Robyn(__file__)


@app.get("/getimage")
def return_image(request):
    return {
        "status": "200",
        "body": pathlib.Path("img2.png").read_bytes(),
        "headers": {"Content-Type": "image/png"}
    }

app.start(port=5000)

**Comment by sansyrox** [comment]
Hey @DhruvThu ,

The issue has been fixed in the latest release. You can find the latest docs here: https://sansyrox.github.io/robyn/#/examples?id=serving-files-to-download
