### ISSUE TITLE
[Feature Request] When Robyn can have a middleware mechanism like flask or django

### ISSUE THREAD

**Issue by shaohaiyang** [sansyrox/robyn#350]
When Robyn can have a middleware mechanism like flask or django such as sessions and security...

![image](https://user-images.githubusercontent.com/2763056/210934212-1130fe5c-a671-4e49-b32d-a7d09b332a8e.png)

---

**Comment by sansyrox** [comment]
Hey @shaohaiyang , Robyn already supports middleware. I will be happy to add more features 😄 

What do you mean by this though? Can you please explain a bit?
>  sessions and security

**Comment by sansyrox** [comment]
Robyn actually has a middleware mechanism(https://sansyrox.github.io/robyn/#/features?id=middlewares) . Feel free to reopen if you feel that we can add something there :D
