### ISSUE TITLE
AttributeError: 'Robyn' object has no attribute 'headers'[BUG]

### ISSUE THREAD

**Issue by QuintinTao** [sansyrox/robyn#353]
**Description**
I use windows 10 Anaconda 201903
I got this error
Traceback (most recent call last):
  File "D:/pywork/DServer/main.py", line 10, in <module>
    app.start(port=5001)
  File "D:\Anaconda\lib\site-packages\robyn\__init__.py", line 164, in start
    process_pool = init_processpool(socket)
  File "D:\Anaconda\lib\site-packages\robyn\__init__.py", line 127, in init_processpool
    self.headers,
AttributeError: 'Robyn' object has no attribute 'headers'

Process finished with exit code 1

**Expected Behavior**

**Screenshots**

**Environment:**
I use windows 10 Anaconda 201903

---

[Optional] **Additional Context**

from robyn import Robyn

app = Robyn(__file__)
@app.get("/")
async def h(request):
    return "Hello, world!"

if __name__ == '__main__':
    app.start(port=5001)
---

**Comment by QuintinTao** [comment]
> @QuintinTao , are you using wsl? And did you install using conda ?
Thank you for your help.
I installed wsl but I don't I think I am using it. I want to use robyn in windows.  I installed it by pip install.

**Comment by QuintinTao** [comment]
when will this windows supported version be released？

**Comment by sansyrox** [comment]
Hey @QuintinTao ,

The fix is ready and this is a high priority issue. Ideally, I would've released it yesterday. However, there a some delays. So, hopefully by today 😄

**Comment by sansyrox** [comment]
Hey @QuintinTao , this issue has been fixed in the latest release 😄

**Comment by QuintinTao** [comment]
> Hey @QuintinTao , this issue has been fixed in the latest release 😄

Thanks.
