### ISSUE TITLE
[BUG] [Windows] Terminal hanging after Ctrl+C is pressed on Robyn server

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#373]
**Description**

When you press `Ctrl+C` to quit Robyn, the terminal hangs on Windows.

**Expected Behavior**

This should not happen.

**Screenshots**

**Environment:**

- Host OS: Windows 10
- Browser:

---

[Optional] **Additional Context**

---

**Comment by Guo-xuejian** [comment]
fine in wsl2, others not(cmd and powershell)
