### ISSUE TITLE
[BUG] Release builds are not working

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#386]
**Description**

I tried to release v0.23.1 two days back but the builds were failing. Need to investigate why.

**Expected Behavior**

To not make them fail 

**Screenshots**

**Environment:**

- Host OS:
- Browser:

---

[Optional] **Additional Context**

---

**Comment by AntoineRR** [comment]
Hey there, what is the issue exactly ? I thought the workflow passed: https://github.com/sansyrox/robyn/actions/runs/4048358023

**Comment by sansyrox** [comment]
Yes @AntoineRR , you're right. I don't know what I saw.

**Comment by sansyrox** [comment]
Closing this.
