### ISSUE TITLE
[Feature Request] Show support for Python versions in the README

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#396]
**Current Behavior**

There is no indication of the support for various Python versions in the Readme. Add it

**Desired Behavior**

---

**Screenshots / Mockups**

**Alternatives**

---

**Comment by Oluwaseun241** [comment]
Can I work on it??

**Comment by sansyrox** [comment]
@Oluwaseun241 , absolutely 😄

**Comment by Oluwaseun241** [comment]
@sansyrox PR has been created please review
