### ISSUE TITLE
using robyn with some frameworks

### ISSUE THREAD

**Issue by eleguns** [sansyrox/robyn#420]
Can we use robyn with fastapi or django?
for example fastapi run with uvicorn
Cna we use robyn instead of uvicorn

**Comment by sansyrox** [comment]
Hey @eleguns 👋 

Robyn is a combination of a web framework and a web server. 
So, Robyn can replace (fastapi and uvicorn) combined.

**Comment by eleguns** [comment]
Oh, Thanks
