### ISSUE TITLE
[Feature Request] Robyn providing Status Codes?

### ISSUE THREAD

**Issue by carlosm27** [sansyrox/robyn#423]
It would be more appropriate if Robyn provides status codes instead of hard coding them?
I create a [branch](https://github.com/carlosm27/robyn/blob/status_codes/robyn/status.py) with "status.py" file in it, it is a copy/paste of Starlette HTTP status code.

Current Behavior
Hard coding the status code like:

```python
return {
        "status_code": 200,
        "body": "some body",
        "type": "text",
  
    }
```

Desired Behavior
Robyn providing status codes like:

```python
return {
        "status_code": status.HTTP_200_OK,
        "body": "Some body",
        "type": "text",

    }
````

**Comment by sansyrox** [comment]
@carlosm27 , that's a great idea. Can you open a PR? We can store them in an enum too.

**Comment by carlosm27** [comment]
@sansyrox Yes, I think an enum will be more appropriate.
