### ISSUE TITLE
Convert the integer status code to the status code enums

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#435]
We recently created a `status_code.py` file (https://github.com/sansyrox/robyn/blob/main/robyn/status_codes.py) , which contains an enum for all the status codes.

However, we are still using integer status codes in our codebase(not the tests but the main code). We would like to replace it with the enum values.

**Comment by khanra17** [comment]
Upon reviewing your codebase, I noticed that you are not using hardcoded integers in your main code, except in the tests. Please let me know if I am missing something, or if there are other areas where I can contribute.

**Comment by Mr-Sunglasses** [comment]
@sansyrox Is there any specific reason we are using `Enums` for the status code isn't it syntactically not good as we need to call `status.HTTPSTATUS.value` which does not look right sometimes? Can we make the approach that FastAPI and starlette are doing which is just `status.HTTPSTATUS` ref . [status.py](https://github.com/encode/starlette/blob/master/starlette/status.py) of starlette.

**Comment by sansyrox** [comment]
@Mr-Sunglasses , apologies for the late revert. This comment missed my eye.

> Can we make the approach that FastAPI and starlette are doing which is just status.HTTPSTATUS ref . [status.py](https://github.com/encode/starlette/blob/master/starlette/status.py) of starlette.

There is no specific reason. I agree we should proceed this way 😄

**Comment by Mr-Sunglasses** [comment]
ok awesome I'll implement it by this weekend.

**Comment by IdoKendo** [comment]
Why not use the standard library's `http.HTTPStatus`?

Feels like we're adding some boilerplate for some syntactic sugar.
E.g. `HTTPStatus.OK.value` is replaced by the current `StatusCodes.HTTP_200_OK.value` or the proposed `StatusCodes.HTTP_200_OK`

My preference would be to remove `status_code.py` and use the stdlib instead, honestly.

**Comment by Mr-Sunglasses** [comment]
> Why not use the standard library's `http.HTTPStatus`?
> 
> Feels like we're adding some boilerplate for some syntactic sugar. E.g. `HTTPStatus.OK.value` is replaced by the current `StatusCodes.HTTP_200_OK.value` or the proposed `StatusCodes.HTTP_200_OK`
> 
> My preference would be to remove `status_code.py` and use the stdlib instead, honestly.

Hey @IdoKendo are you ref. to [HTTP in stdlib](https://docs.python.org/3/library/http.html), yes we can also do that, but ideally, most of the backend frameworks have their own HTTP status code. Let's take the view of other people on this issue.

**Comment by IdoKendo** [comment]
@Mr-Sunglasses Yeah, that's what I mean. Sure, I am not trying to impose my own preference, just wondering what's the benefit here. Let's see what others are thinking.

**Comment by khanra17** [comment]
> 

Why is this marked as good first and why you didn't reply?

**Comment by sansyrox** [comment]
Hey @IdoKendo @Mr-Sunglasses , 👋 

The reason why we are proposing to have `status_code.py` is mostly for better syntactic developer experience. `StatusCodes.HTTP_200_OK.value` is not a nice way IMO. When we can do `StatusCodes.HTTP_200_OK` .

Let me know what you all think 😄

**Comment by IdoKendo** [comment]
> Hey @IdoKendo @Mr-Sunglasses , 👋
> 
> The reason why we are proposing to have `status_code.py` is mostly for better syntactic developer experience. `StatusCodes.HTTP_200_OK.value` is not a nice way IMO. When we can do `StatusCodes.HTTP_200_OK` .
> 
> Let me know what you all think 😄

Hmm, I see your point, though, in my opinion, I would still prefer to use the standard library even if it's a little less "sugary".
But as I see it's the general preference to go with custom names, I stand down 😅
