### ISSUE TITLE
Can't access new or updated route while on dev option

### ISSUE THREAD

**Issue by ibnbay99** [sansyrox/robyn#439]
### Bug Description

Dev option for hot reloading is not working to recompile python code into rust object

### Steps to Reproduce

1. Start simple app.py,  `python app.py --dev`

```
from robyn import Robyn

app = Robyn(__file__)


@app.get("/")
async def hello(request):
    return "Hello World"


app.start(port=8080)
```
2. Update return value of hello function, or add new route
DEBUG:fsevents:NativeEvent(path="/pp.py", inode=30320742, flags=11400, id=285275140): is_file, is_inode_meta_mod, is_modified
DEBUG:fsevents:NativeEvent(path="web_api/app.py~", inode=30678452, flags=15700, id=285275143): is_coalesced, is_created, is_file, is_inode_meta_mod, is_modified, is_owner_change, is_removed
DEBUG:fsevents:queue_event <FileModifiedEvent: event_type=modified, src_path='web_api/app.py', is_directory=False>
DEBUG:fsevents:queue_event <FileCreatedEvent: event_type=created, src_path='web_api/app.py~', is_directory=False>
DEBUG:fsevents:queue_event <DirModifiedEvent: event_type=modified, src_path='web_api', is_directory=True>
DEBUG:fsevents:queue_event <FileModifiedEvent: event_type=modified, src_path='web_api/app.py~', is_directory=False>
DEBUG:fsevents:queue_event <FileDeletedEvent: event_type=deleted, src_path='web_api/app.py~', is_directory=False>
DEBUG:fsevents:queue_event <DirModifiedEvent: event_type=modified, src_path='web_api', is_directory=True>

3. But when rehit GET root path, still return old value or new route is not available

### Your operating system

on macbook intel, mac os monterey

### Your Python version (`python --version`)

3.10.9

### Your Robyn version

0.25.0

**Comment by Noborita9** [comment]
Just wondering, at the app = Robyn(File)
Is it exactly that?

**Comment by Noborita9** [comment]
Nevermind, I tested it myself and it's happening. Not sure if this is new, I remember that it was working, That or my memory is going to get nervous 😰

**Comment by sansyrox** [comment]
@ibnbay99 , thank you for opening the issue. This is really strange. I will have a look

**Comment by AntoineRR** [comment]
@sansyrox I was able to reproduce the bug, and I think it is linked with how we handle hot reloading currently. We do not populate the router and middleware router again but still use their old values.
I can work on this if you want as I previously reworked the dev flag already.

**Comment by AntoineRR** [comment]
Ok I'll take this subject then :wink:

**Comment by sansyrox** [comment]
@AntoineRR , I was thinking we should introduce some smoke testing for issues like this. I will be happy to write some to help with the PR.

What say?

**Comment by AntoineRR** [comment]
Sound good to me! I'm not sure how to write such tests for now so your help is welcome 😊
