### ISSUE TITLE
Implement Robyn CLI

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#448]
I have had an idea of creating a cli tool for Robyn.

Possible invocation could be like - `python -m robyn --args`

Now, the responsibilities I had in mind was just `initialization` - e.g. - `python -m robyn --create/--init` and then it will walk you through a list of commands to start the project.

But after yesterday's community call(suggested by @AntoineRR )

We can also include features like

- `dev` - running the dev server
- `run` - running the server by setting some environment variables 
- and more features in the future.

**Comment by Oluwaseun241** [comment]
@sansyrox this is a great Idea and would like to work on it as well

**Comment by sansyrox** [comment]
@Oluwaseun241 , perfect 😄 You may proceed

**Comment by Oluwaseun241** [comment]
Can this be written in another language??

**Comment by sansyrox** [comment]
@Oluwaseun241 , This will be deployed at pypi and will be ideally part of this repo only. So, I think we should keep in python. Also, since it will be basically a git clone initially, execution speed will not be a bottleneck here.

**Comment by Oluwaseun241** [comment]
@sansyrox Alright would update you

**Comment by Noborita9** [comment]
@Oluwaseun241 Hi! how are you doing with it? I am kinda interested and wanted to know how it's progressing

**Comment by Oluwaseun241** [comment]
@Noborita9 I've been working on it....if I need help I would definitely hook you up

**Comment by sansyrox** [comment]
@Oluwaseun241 , would it be possible for you to create a draft PR? That way all of us will be able to share some feedback or collaborate with you
