### ISSUE TITLE
Proposal to rename `params` with `path_params`

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#457]
Imo, `params` don't really indicate anything meaningful. We should be referring them as `path_params` and being more explicit

**Comment by carlosm27** [comment]
I was trying to change the `params` in the Request class:

```
@dataclass
class Request:
    queries: dict[str, str]
    headers: dict[str, str]
    path_params: dict[str, str]
    body: Union[str, bytes]
    method: str
    url: Url
```

And change the functions in `base_routes.py` to test the changes:

```
@app.get("/sync/param/:id")
def sync_param(request: Request):
    id = request.path_params["id"]
    return id



```
But when I ran `base_routes.py` a go to `/sync/param/:id` I receive this message: `ERROR:robyn.server:Error while executing route function: AttributeError: 'builtins.Request' object has no attribute 'path_params'` and Internal Server Error message.

**Comment by sansyrox** [comment]
@carlosm27 , only changing params in python will not be sufficient. You will also need to rename the code in rust here - https://github.com/sansyrox/robyn/search?q=params
