### ISSUE TITLE
Payload reached size limit.

### ISSUE THREAD

**Issue by mn3711698** [sansyrox/robyn#463]
Some of my requests  return this prompt. I see that actix has parameters to set this value. Please tell me how to configure it in Robyn

**Comment by sansyrox** [comment]
Hi @mn3711698 👋 

Can you show me the example of the request that was failing for you? 

Right now, we have a hardcoded value that I thought would be sufficient, but I can increase it if need be.

**Comment by mn3711698** [comment]
I send the content of 164K text and it returns this. My business is that there is often a lot of text content being submitted.Can i self-customization or configuration

**Comment by sansyrox** [comment]
@mn3711698 , I have create a feature that will allow easily configurable payloads. It should be released in v0.27.0 , i.e. by Monday. 

I will just re-review it and write proper documentation by tomorrow. 😄

**Comment by sansyrox** [comment]
@mn3711698 , this has been fixed in the latest release - https://github.com/sansyrox/robyn/releases/tag/v0.27.0
