### ISSUE TITLE
[Proposal] Const Requests

### ISSUE THREAD

**Issue by JackThomson2** [sansyrox/robyn#48]
I wonder if we should off an option for a constant response which won't change, this would allow us to never touch python for ultra fast path solutions.

**Comment by sansyrox** [comment]
Hey @JackThomson2 , I don't understand what you mean by this. Constant response as in?

**Comment by JackThomson2** [comment]
For example our hello world request is constant as it always response "HELLO WORLD", so in this case, we could save this rust side, meaning we'd never have to call the python function/

**Comment by sansyrox** [comment]
@JackThomson2 , but hello world is just an example in our scenario. We definitely require variable response for a web server to exist. Maybe I am unable to understand something but I can't see how a fixed function can be helpful. Won't we still require some sort of python to pass the info?

**Comment by JackThomson2** [comment]
It would be a per function opt-in thing, definitely not for every function.

**Comment by sansyrox** [comment]
If it as opt-in what would be the constant part?

**Comment by JackThomson2** [comment]
The response of the functions, as I say in the Hello world, we'd just save that.

**Comment by JackThomson2** [comment]
An example for this could be returning the static index page etc. If it's always returning index there would be no point checking the python function every time

**Comment by sansyrox** [comment]
@JackThomson2 , I understand your proposal now. I think it will be a good addition and can make the response time faster. Also, I have something in mind that will allow us to use the decorator python syntax with it.

**Comment by sansyrox** [comment]
I also will be implementing static file serving after merging your PR. That will be using native rust only imo.

**Comment by sansyrox** [comment]
@JackThomson2 , is this request relevant after the v0.6.0 release?
