### ISSUE TITLE
Improve the router

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#52]
Improve the router. Add the ability to have variable parameters in the routes.

- Consider if we need to use a regex based router | as ripgrep is very fast
- Or we need to use a vanilla stack based router
- Or we need to go all fancy and implement a radix tree (or something similar) ourselves!

**Comment by JackThomson2** [comment]
I think using the actix router library may be a good option

**Comment by sansyrox** [comment]
@JackThomson2 , are you talking about this: https://crates.io/crates/actix-router ?

I am unable to find any documentation for the same.

**Comment by JackThomson2** [comment]
Docs are here: https://docs.rs/actix-router/0.4.0/actix_router/ and there are examples in the repository: https://github.com/actix/actix-net/blob/master/actix-router/examples/flamegraph.rs

**Comment by sansyrox** [comment]
@JackThomson2 , I did read the example, but I am unable to understand what is being done here(https://github.com/actix/actix-net/blob/master/actix-router/examples/flamegraph.rs#L3) .

**Comment by sansyrox** [comment]
The latest router has been implemented: https://github.com/sansyrox/robyn/pull/90
