### ISSUE TITLE
app.add_sub_router Not found

### ISSUE THREAD

**Issue by mn3711698** [sansyrox/robyn#541]
from robyn import Robyn, SubRouter

app = Robyn(__file__)

sub_router = SubRouter("/sub_router")

@sub_router.get("/hello")
def hello():
    return "Hello, world"

web_socket = SubRouter("/web_socket")

@web_socket.message()
async def hello():
    return "Hello, world"

app.add_sub_router(sub_router)

but add_sub_router   function not found
@sansyrox

**Comment by mn3711698** [comment]
v0.33.0

**Comment by sansyrox** [comment]
Hey @mn3711698 👋 

Thanks for the issue.

It should be `app.include_router(sub_router)`. There was a typo in the docs. I have updated it 😄

**Comment by sansyrox** [comment]
Feel free to open this issue if you have any other questions 😄
