### ISSUE TITLE
Link pointing to the wrong destination

### ISSUE THREAD

**Issue by VishnuSanal** [sansyrox/robyn#6]
![image](https://user-images.githubusercontent.com/50027064/122583116-86ba3280-d076-11eb-80d0-ce4ab26114cf.png)

The link in the attached screenshot points [here](https://raw.githubusercontent.com/sansyrox/robyn/main/docs/architecture.md) rather than [here](https://sansyrox.github.io/robyn/#/architecture)!

PS: Awesome work with the project :)

**Comment by sansyrox** [comment]
Thank you, @VishnuSanal . Will fix it!

**Comment by sansyrox** [comment]
Fixed here: https://github.com/sansyrox/robyn/commit/e81fd0209cb67c4dd57f169107612b946748664f
