### ISSUE TITLE
For v0.7.0

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#72]
- [x] Improve the docs!
- [x] Add Python Tests!!!
- [ ] Modularise code
- [x] Add a performance comparison with other frameworks
- [x] Reveal the logo
- [ ] (Maybe) add docs for plugin creation. (Push to 0.8)
- [x] Integrate actix router (Push to 0.8)
- [x] Create the homepage
- [x] Make request object accessible across *all* the routes
- [x] Make headers accessible in every route
- [x] Integrate circle ci testing
- [x] Add rust tests
- [x] Make the server ready for HTTP 1.1
- [x] Add the option of 0.0.0.0
- [x] Add python tests

**Comment by JackThomson2** [comment]
Isn't Actix http 1.1 compliant already?

**Comment by sansyrox** [comment]
This is not with regards to Actix but with the HTTP requirements in
general. e.g. we can't headers in GET requests at this time. And testing
HEAD requests thoroughly and so on...

**Comment by sansyrox** [comment]
Need to move this to a different issue.
