### ISSUE TITLE
Add documentation about deployment

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#93]
We need to add docs about deployment

**Comment by carlosm27** [comment]
Hi, I just try Robyn and deploy the example on Railway.

Example:

```
from robyn import Robyn
import os

app = Robyn(__file__)

@app.get("/")
async def h(request):
    return "Hello, world!"


if __name__ == '__main__':
    app.start(url="0.0.0.0", port=os.getenv("PORT", default=5000))
```
May I write about deployment? Do you have something in mind about the example we should show in the docs?

**Comment by sansyrox** [comment]
@carlosm27 , were you able to deploy Robyn successfully?

**Comment by sansyrox** [comment]
That's great news! Thank you @carlosm27 

> Should I include the process in the documentation 

Please mention the process too. It will allow the new developer to have a better developer experience 😄
